<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="WebApplication2.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    
 

</head>
<body>
    <form id="form1" runat="server">
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" ShowFooter="True" Width="639px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:TemplateField HeaderText="Id" SortExpression="Id">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:LinkButton ID="IdLabel" runat="server">Insert</asp:LinkButton>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="name" SortExpression="name">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="nameTextBox" runat="server"></asp:TextBox>

                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="class" SortExpression="class">
                    <EditItemTemplate>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" Text="*" runat="server" ErrorMessage="select class" ControlToValidate="ClassList"></asp:RequiredFieldValidator>
                <asp:DropDownList ID="ClassList" runat="server"  Text='<%# Bind("class") %>'>
                             <asp:listitem>select class</asp:listitem>
                             <asp:listitem>1</asp:listitem>
                             <asp:ListItem>2</asp:ListItem>
                             <asp:listitem>3</asp:listitem>
                             <asp:listitem>4</asp:listitem>
                             <asp:listitem>5</asp:listitem>
                             <asp:listitem>6</asp:listitem>
                             <asp:listitem>7</asp:listitem>
                             <asp:listitem>8</asp:listitem>
                             <asp:listitem>9</asp:listitem>
                             <asp:listitem>10</asp:listitem>
                             <asp:listitem>11</asp:listitem>
                             <asp:listitem>12</asp:listitem>
                         </asp:DropDownList>                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("class") %>'></asp:Label>
                    </ItemTemplate>
                     <FooterTemplate>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" Text="*" runat="server" ErrorMessage="select class" ControlToValidate="ClassList1"></asp:RequiredFieldValidator>
                         <asp:DropDownList ID="ClassList1" runat="server"  Text='<%# Bind("class") %>'>
                             <asp:listitem>select class</asp:listitem>
                             <asp:listitem>1</asp:listitem>
                             <asp:ListItem>2</asp:ListItem>
                             <asp:listitem>3</asp:listitem>
                             <asp:listitem>4</asp:listitem>
                             <asp:listitem>5</asp:listitem>
                             <asp:listitem>6</asp:listitem>
                             <asp:listitem>7</asp:listitem>
                             <asp:listitem>8</asp:listitem>
                             <asp:listitem>9</asp:listitem>
                             <asp:listitem>10</asp:listitem>
                             <asp:listitem>11</asp:listitem>
                             <asp:listitem>12</asp:listitem>
                         </asp:DropDownList>
                        
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MydatabaseConnectionString %>" DeleteCommand="DELETE FROM [student] WHERE [Id] = @Id" InsertCommand="INSERT INTO [student] ([Id], [name], [class]) VALUES (@Id, @name, @class)" SelectCommand="SELECT * FROM [student]" UpdateCommand="UPDATE [student] SET [name] = @name, [class] = @class WHERE [Id] = @Id">
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Id" Type="Int32" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="class" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="class" Type="Int32" />
                <asp:Parameter Name="Id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:ValidationSummary ID="ValidationSummary1" runat="server" />
    </form>
</body>
</html>
